version: '3'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      # Add any other environment variables here
    restart: unless-stopped
